version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: anas
      MYSQL_USER: db
      MYSQL_PASSWORD: root1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: anas
      MYSQL_PASSWORD: root1234
      MYSQL_DATABASE: db
