name: Check Docker Compose
on:
  push:
    branches:
      - main
jobs:
  docker_test:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Start Docker Compose web
      run: docker compose --file web.yml up -d
    - name: Check Container Status
      run: docker ps
