name: Check Docker Compose
on:
  push:
    branches:
      - main
jobs:
  developpement:
    runs-on: [self-hosted, linux, dev]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Start Docker Compose web
      run: docker compose -f webb.yml up -d
    - name: Check Container Status
      run: docker ps
      
  preprod:
    runs-on: [self-hosted, linux, preprod]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Start Docker Compose web
      run: docker compose -f web.yml up -d
    - name: Check Container Status
      run: docker ps
